### ISSUE TITLE
Can be replaced by apply-loader!pug-loader?

### ISSUE THREAD

**Issue by simon04** [static-dev/pug-static-loader#1]
As per https://github.com/pugjs/pug-loader/pull/27, the official [pug-loader](https://github.com/pugjs/pug-loader/) in combination [apply-loader](https://github.com/mogelbrod/apply-loader) produce the same results.

**Comment by jescalan** [comment]
Awesome, this is great to hear, I'll deprecate this package then. Interested in PR'ing a deprecation notice to the readme?
